--creacion de tablas 
CREATE TABLE clasificacion_pelicula ( id_clasificacion SERIAL NOT NULL, nombre VARCHAR(4) NOT NULL, PRIMARY KEY (id_clasificacion) ); 
CREATE TABLE pelicula ( id_pelicula SERIAL NOT NULL, titulo VARCHAR(27) NOT NULL, descripcion VARCHAR(130) NOT NULL, ano_lanzamiento VARCHAR(4) NOT NULL, duracion SMALLINT NOT NULL, costo_renta DECIMAL NOT NULL, dias_renta SMALLINT NOT NULL, recargo_dano DECIMAL NOT NULL, CLASIFICACION_id INTEGER NOT NULL, PRIMARY KEY (id_pelicula), FOREIGN KEY (CLASIFICACION_id) REFERENCES clasificacion_pelicula (id_clasificacion) ); 
CREATE TABLE actor ( id_actor SERIAL NOT NULL, nombre VARCHAR(12) NOT NULL, apellido VARCHAR(12) NOT NULL, PRIMARY KEY (id_actor) ); 
CREATE TABLE reparto_pelicula ( ACTOR_id INTEGER NOT NULL, PELICULA_id INTEGER NOT NULL, PRIMARY KEY (ACTOR_id, PELICULA_id), FOREIGN KEY (ACTOR_id) REFERENCES actor (id_actor), FOREIGN KEY (PELICULA_id) REFERENCES pelicula (id_pelicula) ); 
CREATE TABLE idioma ( id_idioma SERIAL NOT NULL, nombre VARCHAR(20) NOT NULL, PRIMARY KEY (id_idioma) ); 
CREATE TABLE doblaje_pelicula ( PELICULA_id INTEGER NOT NULL, IDIOMA_id INTEGER NOT NULL, PRIMARY KEY (PELICULA_id, IDIOMA_id), FOREIGN KEY (PELICULA_id) REFERENCES pelicula (id_pelicula), FOREIGN KEY (IDIOMA_id) REFERENCES idioma (id_idioma) ); 
CREATE TABLE categoria ( id_categoria SERIAL NOT NULL, nombre VARCHAR(11) NOT NULL, PRIMARY KEY (id_categoria) ); 
CREATE TABLE categoria_pelicula ( PELICULA_id INTEGER NOT NULL, CATEGORIA_id INTEGER NOT NULL, PRIMARY KEY (PELICULA_id, CATEGORIA_id), FOREIGN KEY (PELICULA_id) REFERENCES pelicula (id_pelicula), FOREIGN KEY (CATEGORIA_id) REFERENCES categoria (id_categoria) ); 
CREATE TABLE pais ( id_pais SERIAL NOT NULL, nombre VARCHAR(37) NOT NULL, PRIMARY KEY (id_pais) ); 
CREATE TABLE ciudad ( id_ciudad SERIAL NOT NULL, nombre VARCHAR(26) NOT NULL, PAIS_id INTEGER NOT NULL, PRIMARY KEY (id_ciudad), FOREIGN KEY (PAIS_id) REFERENCES pais (id_pais) ); 
CREATE TABLE tienda ( id_tienda SERIAL NOT NULL, nombre VARCHAR(8) NOT NULL, direccion VARCHAR(38) NOT NULL, CIUDAD_id INTEGER NOT NULL, PRIMARY KEY (id_tienda), FOREIGN KEY (CIUDAD_id) REFERENCES ciudad (id_ciudad) ); 
CREATE TABLE inventario ( id_inventario SERIAL NOT NULL, TIENDA_id INTEGER NOT NULL, PELICULA_id INTEGER NOT NULL, cantidad_copias SMALLINT NOT NULL, PRIMARY KEY (id_inventario), FOREIGN KEY (TIENDA_id) REFERENCES tienda (id_tienda), FOREIGN KEY (PELICULA_id) REFERENCES pelicula (id_pelicula) ); 
CREATE TABLE cliente ( id_cliente SERIAL NOT NULL, nombre VARCHAR(21) NOT NULL, correo VARCHAR(31) NOT NULL, fecha_registro TIMESTAMP NOT NULL, cliente_activo VARCHAR(2) NOT NULL, direccion VARCHAR(38) NOT NULL, codigo_postal VARCHAR(5) NOT NULL, TIENDA_id INTEGER NOT NULL, CIUDAD_id INTEGER NOT NULL, PRIMARY KEY (id_cliente), FOREIGN KEY (TIENDA_id) REFERENCES tienda (id_tienda), FOREIGN KEY (CIUDAD_id) REFERENCES ciudad (id_ciudad) ); 
CREATE TABLE empleado ( id_empleado SERIAL NOT NULL, nombre VARCHAR(12) NOT NULL, correo VARCHAR(22) NOT NULL, empleado_activo VARCHAR(2) NOT NULL, TIENDA_id INTEGER NOT NULL, usuario VARCHAR(4) NOT NULL, contrasena VARCHAR(40) NOT NULL, direccion VARCHAR(38) NOT NULL, PRIMARY KEY (id_empleado), FOREIGN KEY (TIENDA_id) REFERENCES tienda (id_tienda) ); 
CREATE TABLE renta ( id_renta SERIAL NOT NULL, fecha_renta TIMESTAMP NOT NULL, fecha_retorno TIMESTAMP, monto_pago DECIMAL NOT NULL, fecha_pago TIMESTAMP NOT NULL, CLIENTE_id INTEGER NOT NULL, EMPLEADO_id INTEGER NOT NULL, PELICULA_id INTEGER NOT NULL, PRIMARY KEY (id_renta), FOREIGN KEY (CLIENTE_id) REFERENCES cliente (id_cliente), FOREIGN KEY (PELICULA_id) REFERENCES pelicula (id_pelicula), FOREIGN KEY (EMPLEADO_id) REFERENCES empleado (id_empleado) ); 